### ISSUE TITLE
Compiling in Ubuntu 14.04

### ISSUE THREAD

**Issue by linuzo** [ZhyTeam/ZhyCore#2]
In file included from Main.cpp:4:0:
src/Server.hpp:12:21: fatal error: windows.h: No such file or directory
 #include "windows.h"
                     ^
compilation terminated.

**Comment by PeratX** [comment]
You see, @ZhyMC is not interested in this any more. He is now making his own website (qaqqwq.com)

**Comment by Efforto** [comment]
2333333333火速围观

**Comment by Efforto** [comment]
2333333333火速围观

**Comment by Efforto** [comment]
2333333333火速围观

**Comment by Efforto** [comment]
2333333333火速围观

**Comment by Efforto** [comment]
2333333333火速围观

**Comment by Efforto** [comment]
2333333333火速围观

**Comment by ZhyMC** [comment]
没空写,以后可能有空,我格式写的很清楚.希望有人一起.
还有编译环境正确才可以编译.我这里测试Centos是可以的.
windows.h会在linux环境下呗替换

I have no time to continue the huge project.
The environment should be correct.On my Centos server it compiled well.
'windows.h' will be auto replaced
