### ISSUE TITLE
围观

### ISSUE THREAD

**Issue by Efforto** [ZhyTeam/ZhyCore#3]
zhy是不是又要弃坑了.....

**Comment by Efforto** [comment]
@ZhyMC

**Comment by ZhyMC** [comment]
没空写,以后可能有空,我格式写的很清楚.希望有人一起.
还有编译环境正确才可以编译.我这里测试Centos是可以的.
windows.h会在linux环境下呗替换

I have no time to continue the huge project.
The environment should be correct.On my Centos server it compiled well.
'windows.h' will be auto replaced

**Comment by PeratX** [comment]
We do not encourage you post like this. JUST WAIT
